# Generated by Django 3.0.14 on 2023-09-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20230914_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Watch List Status'),
        ),
    ]
