# Generated by Django 3.0.14 on 2023-09-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.FloatField(default='0', verbose_name='Bid Amount'),
        ),
    ]
