# Generated by Django 3.0.14 on 2023-09-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20230926_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.FloatField(verbose_name='Bid Amount'),
        ),
    ]
