# Generated by Django 3.0.14 on 2023-09-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20230926_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=25, unique=True, verbose_name='Listing Title'),
        ),
    ]
